[package]
name = "automl"
version = "0.3.0"
authors = ["Chris McComb <ccmcc2012@gmail.com>"]
description = "Automated machine learning for classification and regression"
edition = "2021"
readme = "README.md"
repository = "https://github.com/cmccomb/rust-automl"
homepage = "https://github.com/cmccomb/rust-automl"
documentation = "https://docs.rs/automl"
license = "MIT OR Apache-2.0"
keywords = ["machine-learning", "ml", "ai", "smartcore", "automl"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
smartcore = { version = "0.2.1", features=["serde"] }
serde = { version = "1.0.171", features=["derive"] }
serde_yaml = "0.9.23"
bincode = "1.3.3"
itertools = "0.11.0"
comfy-table = "7.0.1"
humantime = "2.1.0"

ndarray = {version = "0.15.3", optional = true}

polars = {version = "0.17.0", features = ["ndarray"], optional = true}
url = {version = "2.2.2", optional = true}
temp-file = {version = "0.1.6", optional = true}
minreq = {version = "2.6.0", optional = true, features = ["json-using-serde", "https"]}
csv-sniffer = { version = "0.3.1", optional = true }

[features]
default = []
nd = ["ndarray"]
csv = ["polars", "nd", "url", "temp-file", "minreq", "csv-sniffer"]